<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Swashbuckle.AspNetCore" />

		<!-- MORYX Core -->
		<PackageReference Include="Moryx" />
		<PackageReference Include="Moryx.Model" />
		<PackageReference Include="Moryx.Model.Sqlite" />
		<PackageReference Include="Moryx.Runtime.Kernel" />

		<!-- MORYX Maintenance-->
		<PackageReference Include="Moryx.Runtime.Endpoints" />
		<PackageReference Include="Moryx.CommandCenter.Web" />

		<!--MORYX Abstraction Layer-->
		<PackageReference Include="Moryx.Products.Management" />
		<PackageReference Include="Moryx.Resources.Management" />
		
		<PackageReference Include="Moryx.Launcher" />

		<!-- MORYX CS -->
		<PackageReference Include="Moryx.Orders.Management" />
		<PackageReference Include="Moryx.ControlSystem.Jobs.Endpoints" />
		<PackageReference Include="Moryx.ControlSystem.ProcessEngine" />
		<PackageReference Include="Moryx.ControlSystem.ProcessEngine.Web" />
		<PackageReference Include="Moryx.ControlSystem.Processes.Endpoints" />
		<PackageReference Include="Moryx.ControlSystem.SetupProvider" />
		<PackageReference Include="Moryx.Notifications.Publisher" />
		<PackageReference Include="Moryx.ControlSystem.VisualInstructions.Endpoints" />
		<PackageReference Include="Moryx.ControlSystem.WorkerSupport" />
		<PackageReference Include="Moryx.ControlSystem.WorkerSupport.Web" />
		<PackageReference Include="Moryx.Notifications.Endpoints" />
		<PackageReference Include="Moryx.Notifications.Web" />
		<PackageReference Include="Moryx.Orders.Endpoints" />
		<PackageReference Include="Moryx.Orders.Web" />
		<PackageReference Include="Moryx.Resources.AssemblyInstruction" />

	</ItemGroup>

</Project>
